set(CPP_GENERATED_CORE_ROOT "${CMAKE_CURRENT_LIST_DIR}")
set(CPP_GENERATED_CONFIG_HEADER "${CPP_GENERATED_CORE_ROOT}/helcpp_config.hpp")
set(CPP_GENERATED_UNITY_SOURCE "${CPP_GENERATED_CORE_ROOT}/generated_unity.cpp")
set(CPP_GENERATED_FEATURE_MANIFEST_HEADER "${CPP_GENERATED_CORE_ROOT}/runtime/feature_manifest.hpp")